### PR TITLE
#27 - added local storage support, when toggling between texts the da…

### PR DESCRIPTION
**Pull request by lchayoun**
…ta will be saved to the localstorage, tags of the current text will be lost in case of a crash but the rest of the  texts will be saved, @omishali - this will also support continues work without saving

### CODE REVIEW

**Comment by lchayoun** [comment]
#5 - this will support continues work locally

**Comment by omishali** [comment]
Hi Liel,
I didn't understand the essence of the new feature. What do you mean by "this
will also support continues work without saving"?
Oren

2016-12-30 13:35 GMT+02:00 lchayoun <notifications@github.com>:

**Comment by lchayoun** [comment]
hi @omishali , I have added something called "Local Storage", I'm saving the data (on page change) on your browser internal storage, then if you move between text and hit refresh (or close the browser) and then come back to the site, you will continue from the same point (Note that new tags in the current page will be lost).

**Comment by omishali** [comment]
Nice, I will check it out.

בתאריך 4 בינו׳ 2017 9:28 אחה״צ,‏ "lchayoun" <notifications@github.com> כתב:

**Pull request merged**
